ci:
  autofix_prs: false
  autoupdate_schedule: monthly
  submodules: false

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --diff
          - --check
          - --profile=black
          - --line-length=79
        exclude: (migrations|task_manager/settings.py)

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --diff
          - --check
          - --line-length=79
        exclude: (migrations|task_manager/settings.py|task_manager/asgi.py|manage.py|task_manager/wsgi.py)

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: (migrations|task_manager/settings.py)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
